<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<!-- This file is run automatically when the project is built. https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019 
		 -->
	<Target Name="GovUkFrontend_CheckGovUkFrontendPackage" BeforeTargets="BeforeBuild">
		<PropertyGroup>
			<GovUkPackageFolder>$(MsBuildThisFileDirectory)..\node_modules\govuk-frontend</GovUkPackageFolder>
		</PropertyGroup>

		<Exec Command="where node" Condition="!Exists('$(GovUkPackageFolder)')" ConsoleToMsBuild="true" IgnoreExitCode="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="CheckForNode" />
		</Exec>
		<Error Text="Node.js is not installed. Node.js is required to install the govuk-frontend package which contains the conformance tests. See https://nodejs.org" Condition="$(CheckForNode.Contains('Could not find files'))" />
		<Error Text="govuk-frontend NPM package not found. Run 'npm run govuk' in the root of this repo, $(SolutionDir)." Condition="!Exists('$(GovUkPackageFolder)')" />
</Target>
</Project>
