trigger: none

pool:
  vmImage: "windows-2022"

variables:
  - name: solution
    value: "$(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/GovUk.Frontend.slnx"
  - name: buildPlatform
    value: "Any CPU"
  - name: buildConfiguration
    value: "Release"
  - name: pushPackages
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]

resources:
  repositories:
    - repository: hooks
      type: git
      name: TPR/Tools-TPRGitHooks
      ref: release/1.0.1
    - repository: pipelines
      type: git
      name: TPR/Tools-AzurePipelines
      ref: release/1.1.0

steps:
  - checkout: self
    submodules: true
  - checkout: hooks
  - checkout: pipelines

  - template: git-secrets.steps.yml@hooks
    parameters:
      repoPath: $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions

  - task: NodeTool@0
    inputs:
      versionSpec: "24.13.1"
    displayName: Set Node version

  - task: Cache@2
    displayName: Cache node_modules
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/package-lock.json'
      path: $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/node_modules
      cacheHitVar: CACHE_RESTORED

  - task: Cache@2
    displayName: Cache Tpr.GovUk.Frontend.Umbraco\Backoffice\node_modules
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/ThePensionsRegulator.GovUk.Frontend.Umbraco/Backoffice/package-lock.json'
      path: $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/ThePensionsRegulator.GovUk.Frontend.Umbraco/Backoffice/node_modules
      cacheHitVar: GOVUK_UMBRACO_BACKOFFICE_CACHE_RESTORED

  - task: Cache@2
    displayName: Cache Tpr.Frontend.Umbraco\Backoffice\node_modules
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/ThePensionsRegulator.Frontend.Umbraco/Backoffice/package-lock.json'
      path: $(Build.SourcesDirectory)/govuk-frontend-aspnetcore-extensions/ThePensionsRegulator.Frontend.Umbraco/Backoffice/node_modules
      cacheHitVar: TPR_UMBRACO_BACKOFFICE_CACHE_RESTORED

  - task: Npm@1
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions'
      customCommand: "audit --level moderate --groups dependencies"
    displayName: npm audit root project

  - task: Npm@1
    inputs:
      command: ci
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions'
    displayName: npm ci
    condition: ne(variables.CACHE_RESTORED, 'true')

  - task: Npm@1
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.GovUk.Frontend.Umbraco\Backoffice'
      customCommand: "audit --level moderate --groups dependencies"
    displayName: npm audit GOV.UK backoffice

  - task: Npm@1
    inputs:
      command: ci
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.GovUk.Frontend.Umbraco\Backoffice'
    displayName: npm ci GOV.UK backoffice
    condition: ne(variables.GOVUK_UMBRACO_BACKOFFICE_CACHE_RESTORED, 'true')

  - task: Npm@1
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Frontend.Umbraco\Backoffice'
      customCommand: "audit --level moderate --groups dependencies"
    displayName: npm audit TPR backoffice

    - task: Npm@1
    inputs:
      command: ci
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Frontend.Umbraco\Backoffice'
    displayName: npm ci TPR backoffice
    condition: ne(variables.TPR_UMBRACO_BACKOFFICE_CACHE_RESTORED, 'true')

  - task: Npm@1
    inputs:
      command: custom
      customCommand: run backoffice:ci
      workingDir: '$(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions'
    displayName: npm run backoffice:ci

  - script: |
      cd $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions
      npm test
    displayName: Run JS tests
    continueOnError: false # Test failures should fail the build

  # Do not publish JS test results to the pipeline as Azure DevOps cannot publish both C# and JS results so we have to choose

  - task: NuGetToolInstaller@1
    displayName: Install NuGet

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: "restore"
      arguments: --configuration $(buildConfiguration)
      projects: "$(solution)"
      includeNuGetOrg: true

  - template: security/check-nuget-packages.steps.yml@pipelines
    parameters:
      path: "$(solution)"

  # Build this project first to avoid a race condition with SASS compilation, where ThePensionsRegulator.GovUk.Frontend.Umbraco depends upon this project completing first
  - task: DotNetCoreCLI@2
    displayName: Build ThePensionsRegulator.Frontend
    inputs:
      command: "build"
      arguments: --configuration $(buildConfiguration)
      projects: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Frontend\ThePensionsRegulator.Frontend.csproj

  - task: DotNetCoreCLI@2
    displayName: Build ThePensionsRegulator.Frontend.Umbraco
    inputs:
      command: "build"
      arguments: --configuration $(buildConfiguration)
      projects: |
        $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Frontend.Umbraco\ThePensionsRegulator.Frontend.Umbraco.csproj
        $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Umbraco.Testing\ThePensionsRegulator.Umbraco.Testing.csproj

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
      projects: "$(solution)"

  - task: PublishCodeCoverageResults@2
    displayName: "Publish code coverage"
    inputs:
      summaryFileLocation: $(Agent.TempDirectory)\**\coverage.cobertura.xml
      failIfCoverageEmpty: true

  - task: CopyFiles@2
    displayName: Copy ThePensionsRegulator.GovUk.Frontend package to staging folder
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.GovUk.Frontend\bin\$(buildConfiguration)
      Contents: |
        ThePensionsRegulator.GovUk.Frontend*.nupkg
        ThePensionsRegulator.GovUk.Frontend*.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: CopyFiles@2
    displayName: Copy ThePensionsRegulator.Umbraco.Core package to staging folder
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Umbraco.Core\bin\$(buildConfiguration)
      Contents: |
        ThePensionsRegulator.Umbraco.Core*.nupkg
        ThePensionsRegulator.Umbraco.Core*.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: CopyFiles@2
    displayName: Copy ThePensionsRegulator.Frontend package to staging folder
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Frontend\bin\$(buildConfiguration)
      Contents: |
        ThePensionsRegulator.Frontend*.nupkg
        ThePensionsRegulator.Frontend*.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: CopyFiles@2
    displayName: Copy ThePensionsRegulator.GovUk.Frontend.Umbraco package to staging folder
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.GovUk.Frontend.Umbraco\bin\$(buildConfiguration)
      Contents: |
        ThePensionsRegulator.GovUk.Frontend*.nupkg
        ThePensionsRegulator.GovUk.Frontend*.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: CopyFiles@2
    displayName: Copy ThePensionsRegulator.Frontend.Umbraco package to staging folder
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Frontend.Umbraco\bin\$(buildConfiguration)
      Contents: |
        ThePensionsRegulator.Frontend*.nupkg
        ThePensionsRegulator.Frontend*.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: CopyFiles@2
    displayName: Copy ThePensionsRegulator.Umbraco.Testing package to staging folder
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\govuk-frontend-aspnetcore-extensions\ThePensionsRegulator.Umbraco.Testing\bin\$(buildConfiguration)
      Contents: |
        ThePensionsRegulator.Umbraco.Testing*.nupkg
        ThePensionsRegulator.Umbraco.Testing*.snupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: NuGetCommand@2
    condition: and(succeeded(), eq(variables.pushPackages, true))
    displayName: "Push to nuget.org"
    inputs:
      command: push
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
      nuGetFeedType: external
      publishFeedCredentials: NUGET

  - task: PublishPipelineArtifact@1
    condition: not(eq(variables.pushPackages, true))
    displayName: "Publish packages as artifact"
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: packages
