<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>$(AssemblyName)</Title>
		<Authors>rickmason-tpr</Authors>
		<Company>The Pensions Regulator</Company>
		<Description>GOV.UK Design System components implemented using the block list editor in Umbraco, and classes used to build applications based on these components.</Description>
		<Copyright>The Pensions Regulator</Copyright>
		<PackageProjectUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</PackageProjectUrl>
		<RepositoryUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</RepositoryUrl>
		<PackageReadmeFile>NuGetReadme.md</PackageReadmeFile>
		<PackageIcon>tpr-nuget.png</PackageIcon>
		<RepositoryType>git</RepositoryType>
		<PackageTags>gds govuk gov.uk umbraco blocklist blockgrid umbraco-marketplace</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>$(AssemblyName)</PackageId>
		<Product>$(AssemblyName)</Product>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="sasscompiler.json" />

		<!-- Dont include the Backoffice folder as part of packaging nuget build -->
		<Content Remove="Backoffice\**" />
		
		<!-- Dont include the uSync folder as part of packaging nuget build. Instead pack it in a different folder. -->
		<Content Remove="uSync\**" />
		<None Include="uSync\**\*.config">
			<PackagePath>uSync</PackagePath>
			<Pack>true</Pack>
		</None>

		<!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
		<None Include="Backoffice\public\umbraco-package.json" Pack="false" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Backoffice\package-lock.json" />
		<None Include="Backoffice\package.json" />
		<None Include="Backoffice\tsconfig.json" />
		<Content Include="ThePensionsRegulator.GovUk.Frontend.Umbraco.targets">
		  <PackagePath>build;buildTransitive</PackagePath>
		  <Pack>true</Pack>
		</Content>
		<Content Include="ThePensionsRegulator.GovUk.Frontend.Umbraco.generated.props">
			<PackagePath>build</PackagePath>
			<Pack>true</Pack>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.SassCompiler" Version="1.86.2" />
		<PackageReference Include="TinyMCE.Umbraco" Version="17.2.0" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="17.2.1" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="17.2.1" />
		<PackageReference Include="uSync.BackOffice" Version="17.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ThePensionsRegulator.GovUk.Frontend\ThePensionsRegulator.GovUk.Frontend.csproj" />
		<ProjectReference Include="..\ThePensionsRegulator.Umbraco.Core\ThePensionsRegulator.Umbraco.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\tpr-nuget.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="sasscompiler.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Backoffice\src\blocks\helpers\checkboxes-helper.ts">
	    <SubType>Code</SubType>
	  </None>
	  <None Update="Backoffice\src\blocks\helpers\radios-helper.ts">
	    <SubType>Code</SubType>
	  </None>
	  <None Update="Backoffice\src\blocks\helpers\task-list-helper.ts">
	    <SubType>Code</SubType>
	  </None>
	  <None Update="Backoffice\src\blocks\helpers\accordion-helper.ts">
	    <SubType>Code</SubType>
	  </None>
	  <None Update="NuGetReadme.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="Styles\govuk-frontend.scss">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </None>
	  <None Update="Styles\govuk-umbraco-backoffice.scss">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\_govuk-list.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\govuk-umbraco-backoffice.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\govuk-frontend.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\_backoffice-block-views.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\_backoffice-rich-text-formats.scss" />
	</ItemGroup>
</Project>