<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\build\ThePensionsRegulator.GovUk.Frontend.Umbraco.generated.props"/>
	
	<Target Name="ThePensionsRegulatorGovUkFrontendUmbraco" AfterTargets="ThePensionsRegulatorGovUkFrontend">
		<!-- Determine if the consuming project is a web project. If it isn't then skip copying/generating files. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/@Sdk">
			<Output TaskParameter="Result" ItemName="GovUkFrontendUmbraco_TargetProjectSdk" />
		</XmlPeek>
		<PropertyGroup>
			<GovUkFrontendUmbraco_TargetProjectIsWebProject Condition="@(GovUkFrontendUmbraco_TargetProjectSdk)=='Microsoft.NET.Sdk.Web'">true</GovUkFrontendUmbraco_TargetProjectIsWebProject>
		</PropertyGroup>

		<!-- Copy files from this project to the consuming project. -->
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco not copying uSync and CSS files because the target project is not a web project." Condition="$(GovUkFrontendUmbraco_TargetProjectIsWebProject) != true" Importance="high" />
		<CallTarget Targets="GovUkFrontendUmbraco_CopyFiles" Condition="$(GovUkFrontendUmbraco_TargetProjectIsWebProject) == true" />

		<!-- If the ModelsBuilder out-of-date flag is present, show a helpful warning. -->
		<Warning Text="Umbraco Models Builder models are out-of-date. Go to Settings &gt; Models Builder &gt; Generate models in the Umbraco backoffice to update them." Condition="Exists('$(ProjectDir)Models\ModelsBuilder\ood.flag')" />
	</Target>

	<Target Name="GovUkFrontendUmbraco_CopyFiles">
		<!-- Use the version of this package to find the NuGet package folder, and copy files from the package to the consuming project. -->
		<PropertyGroup>
			<GovUkFrontendUmbraco_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</GovUkFrontendUmbraco_UserProfile>
			<GovUkFrontendUmbraco_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</GovUkFrontendUmbraco_UserProfile>
			<GovUkFrontendUmbraco_uSyncFilesPath>$(GovUkFrontendUmbraco_UserProfile)\.nuget\packages\thepensionsregulator.govuk.frontend.umbraco\$(TprGovUkFrontendUmbracoPackageVersion)\uSync\</GovUkFrontendUmbraco_uSyncFilesPath>
			<GovUkFrontendUmbraco_StaticWebAssetsPath>$(GovUkFrontendUmbraco_UserProfile)\.nuget\packages\thepensionsregulator.govuk.frontend.umbraco\$(TprGovUkFrontendUmbracoPackageVersion)\staticwebassets\ThePensionsRegulator.GovUk.Frontend.Umbraco\</GovUkFrontendUmbraco_StaticWebAssetsPath>
		</PropertyGroup>
		<ItemGroup>
			<uSyncFilesFromGovUkFrontendUmbraco Include="$(GovUkFrontendUmbraco_uSyncFilesPath)**" />
			<GovUkFrontendUmbraco_BackofficeCss Include="$(GovUkFrontendUmbraco_StaticWebAssetsPath)css\govuk-umbraco-backoffice.*" />
		</ItemGroup>

		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco copying uSync files from $(GovUkFrontendUmbraco_uSyncFilesPath) to $(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(uSyncFilesFromGovUkFrontendUmbraco)"
			  DestinationFiles="$(ProjectDir)uSync\%(RecursiveDir)%(Filename)%(Extension)" 
			  SkipUnchangedFiles="true"/>

		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco copying backoffice CSS files from $(GovUkFrontendUmbraco_StaticWebAssetsPath) to $(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(GovUkFrontendUmbraco_BackofficeCss)"
			  DestinationFiles="$(ProjectDir)wwwroot\css\%(RecursiveDir)%(Filename)%(Extension)" 
			  SkipUnchangedFiles="true"/>

		<!-- Rich text editor data types import wwwroot\css\site.css so that consuming projects can add their own styles, including styles for the 'Formats' dropdown.
		     However if there is no site.css the backoffice generates a request with a 404 response, so create a placeholder file to respond to that request. -->
		<PropertyGroup>
			<GenerateUmbracoSiteCss Condition="!Exists('$(ProjectDir)wwwroot\css\site.css') and !Exists('$(ProjectDir)Styles\site.scss')">true</GenerateUmbracoSiteCss>
		</PropertyGroup>
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco generating $(ProjectDir)wwwroot\css\site.css because it does not exist." Importance="high" Condition="$(GenerateUmbracoSiteCss) == true" />
		<ItemGroup>
			<GovUkFrontendUmbracoSiteCssText Include="GovUkFrontendUmbracoSiteCssText">
				<Text>
/* Generated by ThePensionsRegulator.GovUk.Frontend.Umbraco for the Umbraco rich text editor.
   You can delete this file safely and replace it with your own site.css */
				</Text>
			</GovUkFrontendUmbracoSiteCssText>
			<GovUkFrontendUmbracoSiteCss Include="%(GovUkFrontendUmbracoSiteCssText.Text)" />
		</ItemGroup>
		<WriteLinesToFile File="$(ProjectDir)wwwroot\css\site.css" Lines="@(GovUkFrontendUmbracoSiteCss)" Overwrite="False" Condition="$(GenerateUmbracoSiteCss) == true" />

		<!-- Generate .gitignore files so that files copied from this package are not committed to the consuming project's source control. -->
		<ItemGroup>
			<GovUkFrontendUmbracoCssGitIgnoreText Include="GovUkFrontendUmbracoCssGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.GovUk.Frontend.Umbraco
govuk-umbraco-backoffice.css
govuk-umbraco-backoffice.css.map
				</Text>
			</GovUkFrontendUmbracoCssGitIgnoreText>
			<GovUkFrontendUmbracoCssGitIgnore Include="%(GovUkFrontendUmbracoCssGitIgnoreText.Text)" />
		</ItemGroup>
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco generating $(ProjectDir)wwwroot\css\.gitignore to prevent commit of backoffice CSS files copied into the project." Importance="high" Condition="Exists('$(ProjectDir)wwwroot\css')" />
		<WriteLinesToFile File="$(ProjectDir)wwwroot\css\.gitignore" Lines="@(GovUkFrontendUmbracoCssGitIgnore)" Overwrite="True" />

		<ItemGroup>
			<GovUkFrontendUmbracoUSyncGitIgnoreText Include="GovUkFrontendUmbracoUSyncGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.GovUk.Frontend.Umbraco
*
!.gitignore
				</Text>
			</GovUkFrontendUmbracoUSyncGitIgnoreText>
			<GovUkFrontendUmbracoUSyncGitIgnore Include="%(GovUkFrontendUmbracoUSyncGitIgnoreText.Text)" />
		</ItemGroup>
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco generating $(ProjectDir)uSync\.gitignore to prevent commit of uSync files copied into the project." Importance="high" Condition="Exists('$(ProjectDir)uSync')" />
		<WriteLinesToFile File="$(ProjectDir)uSync\ThePensionsRegulator.GovUk.Frontend.Umbraco\.gitignore" Lines="@(GovUkFrontendUmbracoUSyncGitIgnore)" Overwrite="True" />
	</Target>

	<Target Name="GovUkFrontendUmbraco_Cleanup" BeforeTargets="BeforeBuild">
		<!-- Clean up obsolete files from previous versions where they would cause a conflict. -->
		<ItemGroup>
			<GovUkFrontendUmbraco_uSyncVersion Include="v9"/>
			<GovUkFrontendUmbraco_uSyncVersion Include="v17"/>
		</ItemGroup>
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordion.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordion.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsection.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsection.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsectionsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsectionsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsettingsnogrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsettingsnogrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsettingsshared.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukaccordionsettingsshared.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbutton.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbutton.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbuttongroup.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbuttongroup.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbuttongroupsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbuttongroupsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbuttonsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukbuttonsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcaption.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcaption.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcaptionsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcaptionsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckbox.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckbox.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxes.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxes.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxesdivider.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxesdivider.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxessettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxessettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcheckboxsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcssclasses.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukcssclasses.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdateinput.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdateinput.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdateinputsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdateinputsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdetails.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdetails.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdetailssettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdetailssettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdetailssettingsnogrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukdetailssettingsnogrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrormessage.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrormessage.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrormessageprefix.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrormessageprefix.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrormessagesettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrormessagesettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrorsummary.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrorsummary.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrorsummarysettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukerrorsummarysettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfieldset.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfieldset.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfieldsetsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfieldsetsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfileupload.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfileupload.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfileuploadsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukfileuploadsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridcolumn.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridcolumn.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridcolumnclasses.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridcolumnclasses.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridcolumnsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridcolumnsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridfourcolumnlayoutsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridfourcolumnlayoutsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridfourequalcolumns.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridfourequalcolumns.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridfullwidth.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridfullwidth.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonehalf.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonehalf.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonequarter.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonequarter.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonequarterthreequarters.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonequarterthreequarters.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonethird.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonethird.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonethirdtwothirds.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridonethirdtwothirds.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridrow.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridrow.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridrowsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridrowsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridsinglecolumnlayoutsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridsinglecolumnlayoutsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreecolumnlayoutsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreecolumnlayoutsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreeequalcolumns.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreeequalcolumns.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreequarters.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreequarters.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreequartersonequarter.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridthreequartersonequarter.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwocolumnlayoutsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwocolumnlayoutsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwoequalcolumns.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwoequalcolumns.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwothirds.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwothirds.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwothirdsonethird.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukgridtwothirdsonethird.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukheadinglevel.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukheadinglevel.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukhidden.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukhidden.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukhiddensettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukhiddensettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukhint.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukhint.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukinsettext.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukinsettext.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukinsettextsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukinsettextsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukinsettextsettingsnogrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukinsettextsettingsnogrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklabelispageheading.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklabelispageheading.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklegend.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklegend.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklegendispageheading.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklegendispageheading.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklink.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklink.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklinkasbutton.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklinkasbutton.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklinkasbuttonsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklinkasbuttonsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklinksettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuklinksettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukmodelproperty.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukmodelproperty.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuknotificationbanner.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuknotificationbanner.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuknotificationbannersettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuknotificationbannersettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpageheading.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpageheading.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpageheadingsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpageheadingsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpagesettingheadingsize.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpagesettingheadingsize.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpagination.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpagination.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpaginationsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpaginationsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpanel.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpanel.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpanelsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukpanelsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukphasebanner.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukphasebanner.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradio.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradio.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradios.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradios.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradiosdivider.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradiosdivider.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradiosettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradiosettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradiossettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukradiossettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukreadonly.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukreadonly.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksectionbreak.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksectionbreak.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksectionbreaksettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksectionbreaksettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukselect.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukselect.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukselectoption.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukselectoption.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukselectsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukselectsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksinglecheckboxsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksinglecheckboxsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukskiplink.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukskiplink.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycard.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycard.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycardaction.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycardaction.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycardsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycardsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycardsettingsnogrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarycardsettingsnogrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylist.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylist.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistaction.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistaction.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistitem.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistitem.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistitemsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistitemsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistsettingsnogrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuksummarylistsettingsnogrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktask.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktask.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklist.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklist.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklistsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklistsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklistsummary.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklistsummary.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklistsummarysettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasklistsummarysettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasksettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktasksettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextarea.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextarea.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextareasettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextareasettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextinput.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextinput.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextinputsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktextinputsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktypography.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktypography.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktypographysettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govuktypographysettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationcustom.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationcustom.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationdisplayname.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationdisplayname.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationrange.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationrange.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationrequired.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationrequired.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationtext.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukvalidationtext.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukwarningtext.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukwarningtext.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukwarningtextsettings.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukwarningtextsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukwarningtextsettingsnogrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\govukwarningtextsettingsnogrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKAccordionBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKAccordionBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKAccordionSectionBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKAccordionSectionBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKButtons.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKButtons.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKButtonStyle.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKButtonStyle.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKButtonType.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKButtonType.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKCheckboxes.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKCheckboxes.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKFieldHelpBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKFieldHelpBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKFieldsetBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKFieldsetBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridColumnBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridColumnBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridColumnSize.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridColumnSize.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridColumnStacking.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridColumnStacking.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridRowBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKGridRowBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKHeadingLevel.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKHeadingLevel.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKHeadingLevelAccordion.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKHeadingLevelAccordion.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKHeadingSize.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKHeadingSize.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKLinkPicker.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKLinkPicker.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKModelProperty.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKModelProperty.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKNotificationBannerBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKNotificationBannerBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKNotificationBannerType.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKNotificationBannerType.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKPageHeadingSize.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKPageHeadingSize.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKPhase.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKPhase.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRadioButtons.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRadioButtons.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRadiosLayout.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRadiosLayout.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditor.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditor.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorInline.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorInline.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorInlineAndInverse.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorInlineAndInverse.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorNotificationBanner.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorNotificationBanner.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorNotificationBannerHeading.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorNotificationBannerHeading.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorPhaseBanner.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorPhaseBanner.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorSummaryListItem.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorSummaryListItem.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorTask.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorTask.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorText.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKRichTextEditorText.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSectionBreakSize.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSectionBreakSize.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSelectOptions.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSelectOptions.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSummaryCardActions.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSummaryCardActions.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSummaryListActions.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSummaryListActions.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSummaryListBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKSummaryListBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTaskListBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTaskListBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTaskListStatus.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTaskListStatus.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTextInputWidth.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTextInputWidth.config')" />
		<Delete Files="$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTrueOrFalseDefaultsToTrue.config" Condition="Exists('$(ProjectDir)uSync\%(GovUkFrontendUmbraco_uSyncVersion.Identity)\DataTypes\GOVUKTrueOrFalseDefaultsToTrue.config')" />
	</Target>

</Project>
