<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<!-- This file is run automatically when the project is built. https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019 
	     Run a custom command using Dart SASS installed by the AspNetCore.SassCompiler NuGet package. The default package configuration cannot be used
		 because passing the `-load-path` argument needed by the GOV.UK Front End source code only works when using the `-stdin` argument.
		 -->
	<Target Name="DwpFrontend_CheckDwpFrontendPackage" BeforeTargets="BeforeBuild">
		<PropertyGroup>
			<DwpPackageFolder>$(MsBuildThisFileDirectory)..\node_modules\dwp-frontend</DwpPackageFolder>
		</PropertyGroup>

		<Exec Command="where node" Condition="!Exists('$(DwpPackageFolder)')" ConsoleToMsBuild="true" IgnoreExitCode="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="CheckForNode" />
		</Exec>
		<Error Text="Node.js is not installed. Node.js is required to install the govuk-frontend package which contains the conformance tests. See https://nodejs.org" Condition="$(CheckForNode.Contains('Could not find files'))" />
		<Exec Command="where yarn" Condition="!Exists('$(DwpPackageFolder)')" ConsoleToMsBuild="true" IgnoreExitCode="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="CheckForYarn" />
		</Exec>
		<Error Text="Yarn Classic is required to install the govuk-frontend package which contains the conformance tests. Run 'npm install --global yarn'. If you get an error UNABLE_TO_GET_ISSUER_CERT_LOCALLY you need to click the padlock next to any site in the address bar of your browser, and download the CA certificate for your network in .PEM format. Then set the environment variable NODE_EXTRA_CA_CERTS to the path to that certificate, and restart Visual Studio." Condition="$(CheckForYarn.Contains('Could not find files'))" />
		<Message Text="Dwp Frontend NPM package not found. Running 'yarn install'." Condition="!Exists('$(DwpPackageFolder)')" />
		<Exec Command="yarn install" WorkingDirectory="$(MsBuildThisFileDirectory).." Condition="!Exists('$(DwpPackageFolder)')" />
	</Target>

	<Target Name="TprFrontend_BuildSass" BeforeTargets="BeforeBuild">
		<PropertyGroup>
			<UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</UserProfile>
			<UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</UserProfile>
		</PropertyGroup>
		<Message Text="Run SassCompiler $(MSBuildProjectFullPath)" Importance="high"/>
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/ItemGroup/PackageReference[@Include='AspNetCore.SassCompiler']/@Version">
			<Output TaskParameter="Result" ItemName="SassCompilerVersion" />
		</XmlPeek>
		<PropertyGroup>
			<SassCompilerVersion>@(SassCompilerVersion)</SassCompilerVersion>
			<SassPath>$(UserProfile)\.nuget\packages\aspnetcore.sasscompiler\$(SassCompilerVersion)\runtimes\win-x64\src\</SassPath>
			<GovUkFrontEndFolder>$(MsBuildThisFileDirectory)..\lib\govuk-frontend\packages\govuk-frontend\src</GovUkFrontEndFolder>
			<GovUkFrontEndExtensionsFolder>$(MsBuildThisFileDirectory)..\GovUk.Frontend.AspNetCore.Extensions\Styles\</GovUkFrontEndExtensionsFolder>
			<SourceFolder>$(MsBuildThisFileDirectory)Styles\</SourceFolder>
			<TargetFolder>$(MsBuildThisFileDirectory)wwwroot\</TargetFolder>
		</PropertyGroup>
		<Exec Command="powershell -NonInteractive -NoProfile Get-Content &quot;$(SourceFolder)tpr.scss&quot; | &quot;$(SassPath)dart.exe&quot; &quot;$(SassPath)sass.snapshot&quot; --stdin --quiet-deps --load-path=$(GovUkFrontEndFolder) --load-path=$(GovUkFrontEndExtensionsFolder) --load-path=$(SourceFolder) $(TargetFolder)tpr\tpr.css"/>
		<Message Text="SassCompiler complete for $(MSBuildProjectFullPath)" Importance="high"/>
	</Target>

</Project>
