<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="ThePensionsRegulatorFrontend" AfterTargets="ThePensionsRegulatorGovUkFrontend">
		<!-- Look for the PackageReference to this package to get the current version.
			 Use that version to find the NuGet package folder, and copy SASS files to the Styles folder in the consuming project.
			 If this package is a transitive dependency the PackageReference will not be found, so show a message.
		-->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/ItemGroup/PackageReference[@Include='ThePensionsRegulator.Frontend']/@Version">
			<Output TaskParameter="Result" ItemName="TprFrontendVersion" />
		</XmlPeek>

		<!-- Determine if the consuming project is a web project. If it isn't then skip copying/generating files. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/@Sdk">
			<Output TaskParameter="Result" ItemName="TprFrontend_TargetProjectSdk" />
		</XmlPeek>
		<PropertyGroup>
			<TprFrontendVersion>@(TprFrontendVersion)</TprFrontendVersion>
			<TprFrontend_HasPackageReferenceToTprFrontend Condition="@(TprFrontendVersion->Count() )>0">true</TprFrontend_HasPackageReferenceToTprFrontend>
			<TprFrontend_TargetProjectIsWebOrRclProject Condition="@(TprFrontend_TargetProjectSdk)=='Microsoft.NET.Sdk.Web' Or @(TprFrontend_TargetProjectSdk)=='Microsoft.NET.Sdk.Razor'">true</TprFrontend_TargetProjectIsWebOrRclProject>
		</PropertyGroup>

		<!-- Copy files from ThePensionsRegulator.GovUk.Frontend to the consuming project if it is a transitive dependency. -->
		<CallTarget Targets="TprFrontend_CopyFromTprGovUkFrontend" Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) == true And $(TprFrontend_HasPackageReferenceToTprFrontend) == true" />

		<!-- Copy files from this project to the consuming project. -->
		<Message Text="ThePensionsRegulator.Frontend not copying SASS files from ThePensionsRegulator.Frontend because the target project is not a web project or Razor class library." Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) != true" Importance="high" />
		<Message Text="ThePensionsRegulator.Frontend not copying SASS files from ThePensionsRegulator.Frontend because it is a transitive dependency without access to the correct path. These may be copied by the package that references ThePensionsRegulator.Frontend or you may need to add a direct reference to ThePensionsRegulator.Frontend." Importance="high"
				 Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) == true And $(TprFrontend_HasPackageReferenceToTprFrontend) != true"/>
		<CallTarget Targets="TprFrontend_CopyFiles" Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) == true And $(TprFrontend_HasPackageReferenceToTprFrontend) == true" />
		<CallTarget Targets="TprFrontend_GenerateFiles" Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) == true" />
	</Target>

	<Target Name="TprFrontend_CopyFromTprGovUkFrontend">
		<!-- Look for the PackageReference to ThePensionsRegulator.Frontend, which we know exists because the current target only runs if it does. 
		     Get the version, which we can use to find the paths to transitive packages. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/ItemGroup/PackageReference[@Include='ThePensionsRegulator.Frontend']/@Version">
			<Output TaskParameter="Result" ItemName="TprFrontend_CopyFromTprGovUkFrontend_TprFrontendVersion" />
		</XmlPeek>

		<PropertyGroup>
			<TprFrontend_CopyFromTprGovUkFrontend_TprFrontendVersion>@(TprFrontend_CopyFromTprGovUkFrontend_TprFrontendVersion)</TprFrontend_CopyFromTprGovUkFrontend_TprFrontendVersion>
		</PropertyGroup>

		<!-- Look for the PackageReference to ThePensionsRegulator.GovUk.Frontend to get the current version. If it's missing then 
		     ThePensionsRegulator.GovUk.Frontend is a transitive dependency of this package, and will have been unable to copy 
			 govuk-frontend SASS files to the Styles folder of the consuming project.
			 
			 If ThePensionsRegulator.GovUk.Frontend is a transitive dependency find its version in the metadata of ThePensionsRegulator.Frontend. 
			 Use the version of ThePensionsRegulator.GovUk.Frontend to find its NuGet package folder, and copy govuk-frontend SASS files to the 
			 Styles folder in the consuming project.
		-->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/ItemGroup/PackageReference[@Include='ThePensionsRegulator.GovUk.Frontend']/@Version">
			<Output TaskParameter="Result" ItemName="TprGovUkFrontendVersion" />
		</XmlPeek>
		<PropertyGroup>
			<HasPackageReferenceForTprGovUkFrontend Condition="@(TprGovUkFrontendVersion->Count() )==0">false</HasPackageReferenceForTprGovUkFrontend>
			<TprFrontend_CopyFromTprGovUkFrontend_StylesFolderExists Condition="Exists('$(ProjectDir)Styles')">true</TprFrontend_CopyFromTprGovUkFrontend_StylesFolderExists>
			<TprFrontend_CopyFromTprGovUkFrontend_CopySassFiles Condition="$(HasPackageReferenceForTprGovUkFrontend) == false And $(TprFrontend_CopyFromTprGovUkFrontend_StylesFolderExists) == true">true</TprFrontend_CopyFromTprGovUkFrontend_CopySassFiles>
			<TprFrontend_CopyFromTprGovUkFrontend_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</TprFrontend_CopyFromTprGovUkFrontend_UserProfile>
			<TprFrontend_CopyFromTprGovUkFrontend_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</TprFrontend_CopyFromTprGovUkFrontend_UserProfile>
		</PropertyGroup>
		
		<XmlPeek XmlInputPath="$(TprFrontend_CopyFromTprGovUkFrontend_UserProfile)\.nuget\packages\thepensionsregulator.frontend\$(TprFrontend_CopyFromTprGovUkFrontend_TprFrontendVersion)\thepensionsregulator.frontend.nuspec"
			 Query="nu:package/nu:metadata/nu:dependencies/nu:group[@targetFramework = '$(TargetFramework)']/nu:dependency[@id = 'ThePensionsRegulator.GovUk.Frontend']/@version"
			 Namespaces="&lt;Namespace Prefix='nu' Uri='http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd' /&gt;"
			 Condition="$(TprFrontend_CopyFromTprGovUkFrontend_CopySassFiles) == true">
			<Output TaskParameter="Result" ItemName="TprGovUkFrontendVersion" />
		</XmlPeek>
		<PropertyGroup>
			<TprGovUkFrontendVersion>@(TprGovUkFrontendVersion)</TprGovUkFrontendVersion>
			<TprGovUkFrontendSassFolder>$(TprFrontend_CopyFromTprGovUkFrontend_UserProfile)\.nuget\packages\thepensionsregulator.govuk.frontend\$(TprGovUkFrontendVersion)\contentFiles\any\$(TargetFramework)\Styles\</TprGovUkFrontendSassFolder>
		</PropertyGroup>
		<ItemGroup>
			<ThePensionsRegulatorGovUkFrontendSassFiles Include="$(TprGovUkFrontendSassFolder)**\*.scss" />
		</ItemGroup>
		<Message Text="Detected ThePensionsRegulator.GovUk.Frontend as a transitive dependency. Copying govuk-frontend SASS files from $(TprGovUkFrontendSassFolder) to $(ProjectDir)." Importance="high"
			     Condition="$(HasPackageReferenceForTprGovUkFrontend) == false" />

		<!-- The following copy task is also configured in ThePensionsRegulator.Frontend.Umbraco.targets in case this package is referenced as a transitive dependency -->
		<Message Text="ThePensionsRegulator.Frontend detected ThePensionsRegulator.GovUk.Frontend as a transitive dependency. Not copying SASS files because $(ProjectDir)Styles does not exist." Importance="high"
				 Condition="$(HasPackageReferenceForTprGovUkFrontend) == false And $(TprFrontend_CopyFromTprGovUkFrontend_StylesFolderExists) != true" />
		<Message Text="ThePensionsRegulator.Frontend detected ThePensionsRegulator.GovUk.Frontend as a transitive dependency. Copying SASS files from $(ThePensionsRegulatorGovUkFrontendSassFiles) to $(ProjectDir)." Importance="high"
			     Condition="$(TprFrontend_CopyFromTprGovUkFrontend_CopySassFiles) == true" />
		<Copy SourceFiles="@(ThePensionsRegulatorGovUkFrontendSassFiles)"
		      DestinationFiles="$(ProjectDir)Styles\%(RecursiveDir)%(Filename)%(Extension)"
			  Condition="$(TprFrontend_CopyFromTprGovUkFrontend_CopySassFiles) == true" />
	</Target>

	<Target Name="TprFrontend_CopyFiles">
		<!-- Look for the PackageReference to ThePensionsRegulator.Frontend, which we know exists because the current target only runs if it does. 
		     Get the version, which we can use to find the paths to transitive packages. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/ItemGroup/PackageReference[@Include='ThePensionsRegulator.Frontend']/@Version">
			<Output TaskParameter="Result" ItemName="TprFrontend_CopyFiles_TprFrontendVersion" />
		</XmlPeek>

		<PropertyGroup>
			<TprFrontend_CopyFiles_TprFrontendVersion>@(TprFrontend_CopyFiles_TprFrontendVersion)</TprFrontend_CopyFiles_TprFrontendVersion>
			<TprFrontend_CopyFiles_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</TprFrontend_CopyFiles_UserProfile>
			<TprFrontend_CopyFiles_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</TprFrontend_CopyFiles_UserProfile>
		</PropertyGroup>

		<PropertyGroup>
			<TprFrontendSassFolder>$(TprFrontend_CopyFiles_UserProfile)\.nuget\packages\thepensionsregulator.frontend\$(TprFrontend_CopyFiles_TprFrontendVersion)\contentFiles\any\$(TargetFramework)\Styles\</TprFrontendSassFolder>
			<TprFrontend_CopyFiles_StylesFolderExists Condition="Exists('$(ProjectDir)Styles')">true</TprFrontend_CopyFiles_StylesFolderExists>
		</PropertyGroup>
		<ItemGroup>
			<TprFrontendSassFiles Include="$(TprFrontendSassFolder)**\*.scss" />
		</ItemGroup>

		<!-- The following copy task is also configured in ThePensionsRegulator.Frontend.Umbraco.targets in case this package is referenced as a transitive dependency -->
		<Message Text="ThePensionsRegulator.Frontend not copying SASS files because $(ProjectDir)Styles does not exist." Importance="high" Condition="$(TprFrontend_CopyFiles_StylesFolderExists) != true" />
		<Message Text="ThePensionsRegulator.Frontend copying SASS files from $(TprFrontendSassFolder) to $(ProjectDir)" Importance="high" Condition="$(TprFrontend_CopyFiles_StylesFolderExists) == true"/>
		<Copy SourceFiles="@(TprFrontendSassFiles)"
			  DestinationFiles="$(ProjectDir)Styles\%(RecursiveDir)%(Filename)%(Extension)"
			  Condition="$(TprFrontend_CopyFiles_StylesFolderExists) == true"/>
	</Target>

	<Target Name="TprFrontend_GenerateFiles">
		<!-- Generate a .gitignore so that SASS files from the ThePensionsRegulator.Frontend package are not committed to the consuming project's source control.	 
			 Only do that if the folder exists, otherwise they'll also get created in a project with no interest in SASS.  -->
		<PropertyGroup>
			<TprFrontend_GenerateFiles_StylesFolderExists Condition="Exists('$(ProjectDir)Styles')">true</TprFrontend_GenerateFiles_StylesFolderExists>
		</PropertyGroup>

		<Message Text="ThePensionsRegulator.Frontend generating $(ProjectDir)Styles\tpr\.gitignore to prevent commit of SASS files copied into the project." Importance="high" Condition="$(TprFrontend_GenerateFiles_StylesFolderExists) == true" />
		<ItemGroup>
			<ThePensionsRegulatorFrontendGitIgnoreText Include="ThePensionsRegulatorFrontendGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.Frontend
*
!.gitignore
				</Text>
			</ThePensionsRegulatorFrontendGitIgnoreText>
			<ThePensionsRegulatorFrontendGitIgnore Include="%(ThePensionsRegulatorFrontendGitIgnoreText.Text)" />
		</ItemGroup>
		<WriteLinesToFile File="$(ProjectDir)Styles\tpr\.gitignore" Lines="@(ThePensionsRegulatorFrontendGitIgnore)" Overwrite="True" Condition="$(TprFrontend_GenerateFiles_StylesFolderExists) == true" />
	</Target>
	</Project>
