<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\build\ThePensionsRegulator.Frontend.generated.props"/>
	
	<Target Name="ThePensionsRegulatorFrontend" AfterTargets="ThePensionsRegulatorGovUkFrontend">
		<!-- Determine if the consuming project is a web project. If it isn't then skip copying/generating files. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/@Sdk">
			<Output TaskParameter="Result" ItemName="TprFrontend_TargetProjectSdk" />
		</XmlPeek>
		<PropertyGroup>
			<TprFrontend_TargetProjectIsWebOrRclProject Condition="@(TprFrontend_TargetProjectSdk)=='Microsoft.NET.Sdk.Web' Or @(TprFrontend_TargetProjectSdk)=='Microsoft.NET.Sdk.Razor'">true</TprFrontend_TargetProjectIsWebOrRclProject>
		</PropertyGroup>

		<!-- Copy files from this project to the consuming project. -->
		<Message Text="ThePensionsRegulator.Frontend not copying SASS files because the target project is not a web project or Razor class library." Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) != true" Importance="high" />
		<CallTarget Targets="TprFrontend_CopyFiles" Condition="$(TprFrontend_TargetProjectIsWebOrRclProject) == true" />
	</Target>

	<Target Name="TprFrontend_CopyFiles">
		<!-- Use the version of this package to find the NuGet package folder, and copy files from the package to the consuming project. -->
		<PropertyGroup>
			<TprFrontend_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</TprFrontend_UserProfile>
			<TprFrontend_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</TprFrontend_UserProfile>
			<TprFrontendSassFolder>$(TprFrontend_UserProfile)\.nuget\packages\thepensionsregulator.frontend\$(TprFrontendPackageVersion)\Styles\</TprFrontendSassFolder>
			<TprFrontend_StylesFolderExists Condition="Exists('$(ProjectDir)Styles')">true</TprFrontend_StylesFolderExists>
		</PropertyGroup>
		<ItemGroup>
			<TprFrontendSassFiles Include="$(TprFrontendSassFolder)**\*.scss" />
		</ItemGroup>

		<!-- The following copy task is also configured in ThePensionsRegulator.Frontend.Umbraco.targets in case this package is referenced as a transitive dependency -->
		<Message Text="ThePensionsRegulator.Frontend not copying SASS files because $(ProjectDir)Styles does not exist." Importance="high" Condition="$(TprFrontend_StylesFolderExists) != true" />
		<Message Text="ThePensionsRegulator.Frontend copying SASS files from $(TprFrontendSassFolder) to $(ProjectDir)" Importance="high" Condition="$(TprFrontend_StylesFolderExists) == true"/>
		<Copy SourceFiles="@(TprFrontendSassFiles)"
			  DestinationFiles="$(ProjectDir)Styles\%(RecursiveDir)%(Filename)%(Extension)"
			  Condition="$(TprFrontend_StylesFolderExists) == true"
			  SkipUnchangedFiles="true"/>

		<!-- Generate a .gitignore so that SASS files from the ThePensionsRegulator.Frontend package are not committed to the consuming project's source control.	 
			 Only do that if the folder exists, otherwise they'll also get created in a project with no interest in SASS.  -->
		<Message Text="ThePensionsRegulator.Frontend generating $(ProjectDir)Styles\tpr\.gitignore to prevent commit of SASS files copied into the project." Importance="high" Condition="$(TprFrontend_StylesFolderExists) == true" />
		<ItemGroup>
			<ThePensionsRegulatorFrontendGitIgnoreText Include="ThePensionsRegulatorFrontendGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.Frontend
*
!.gitignore
				</Text>
			</ThePensionsRegulatorFrontendGitIgnoreText>
			<ThePensionsRegulatorFrontendGitIgnore Include="%(ThePensionsRegulatorFrontendGitIgnoreText.Text)" />
		</ItemGroup>
		<WriteLinesToFile File="$(ProjectDir)Styles\tpr\.gitignore" Lines="@(ThePensionsRegulatorFrontendGitIgnore)" Overwrite="True" Condition="$(TprFrontend_StylesFolderExists) == true" />
	</Target>
	</Project>
