<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\build\ThePensionsRegulator.Frontend.Umbraco.generated.props"/>

	<Target Name="ThePensionsRegulatorFrontendUmbraco" AfterTargets="ThePensionsRegulatorFrontend;ThePensionsRegulatorGovUkFrontendUmbraco">
		<!-- Determine if the consuming project is a web project. If it isn't then skip copying/generating files. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/@Sdk">
			<Output TaskParameter="Result" ItemName="TprFrontendUmbraco_TargetProjectSdk" />
		</XmlPeek>
		<PropertyGroup>
			<TprFrontendUmbraco_TargetProjectIsWebProject Condition="@(TprFrontendUmbraco_TargetProjectSdk)=='Microsoft.NET.Sdk.Web'">true</TprFrontendUmbraco_TargetProjectIsWebProject>
		</PropertyGroup>

		<!-- Copy files from this project to the consuming project. It's important to do this AFTER copying files for 
		     ThePensionsRegulator.GovUk.Frontend.Umbraco so that we can overwrite them with TPR customisations.
		-->
		<Message Text="ThePensionsRegulator.Frontend.Umbraco not copying uSync and backoffice CSS files because the target project is not a web project." Condition="$(TprFrontendUmbraco_TargetProjectIsWebProject) != true" Importance="high" />
		<CallTarget Targets="TprFrontendUmbraco_CopyFiles" Condition="$(TprFrontendUmbraco_TargetProjectIsWebProject) == true" />
	</Target>

	<Target Name="TprFrontendUmbraco_CopyFiles">
		<!-- Use the version of this package to find the NuGet package folder, and copy files from the package to the consuming project. -->
		<PropertyGroup>
			<TprFrontendUmbraco_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</TprFrontendUmbraco_UserProfile>
			<TprFrontendUmbraco_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</TprFrontendUmbraco_UserProfile>
			<TprFrontendUmbraco_uSyncFilesPath>$(TprFrontendUmbraco_UserProfile)\.nuget\packages\thepensionsregulator.frontend.umbraco\$(TprFrontendUmbracoPackageVersion)\uSync\</TprFrontendUmbraco_uSyncFilesPath>
			<TprFrontendUmbraco_StaticWebAssetsPath>$(TprFrontendUmbraco_UserProfile)\.nuget\packages\thepensionsregulator.frontend.umbraco\$(TprFrontendUmbracoPackageVersion)\staticwebassets\ThePensionsRegulator.Frontend.Umbraco\</TprFrontendUmbraco_StaticWebAssetsPath>
		</PropertyGroup>
		<ItemGroup>
			<uSyncFilesFromTprFrontendUmbraco Include="$(TprFrontendUmbraco_uSyncFilesPath)**" />
			<TprFrontendUmbraco_BackofficeCss Include="$(TprFrontendUmbraco_StaticWebAssetsPath)css\govuk-umbraco-backoffice.*" />
		</ItemGroup>
		
		<Message Text="ThePensionsRegulator.Frontend.Umbraco copying uSync files from $(TprFrontendUmbraco_uSyncFilesPath) to $(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(uSyncFilesFromTprFrontendUmbraco)"
			DestinationFiles="$(ProjectDir)uSync\%(RecursiveDir)%(Filename)%(Extension)" 
			SkipUnchangedFiles="true"/>

		<Message Text="ThePensionsRegulator.Frontend.Umbraco copying backoffice CSS files from $(TprFrontendUmbraco_StaticWebAssetsPath) to $(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(TprFrontendUmbraco_BackofficeCss)"
			DestinationFiles="$(ProjectDir)wwwroot\css\%(RecursiveDir)%(Filename)%(Extension)"
			SkipUnchangedFiles="true"/>

		<!-- Generate .gitignore files so that files from the ThePensionsRegulator.Frontend.Umbraco package are not committed to the consuming project's source control. 
			 There's no need to generate one for wwwroot\css because this package depends on ThePensionsRegulator.GovUk.Frontend.Umbraco, which already did that.
		-->
		<ItemGroup>
			<TprFrontendUmbracoUSyncGitIgnoreText Include="TprFrontendUmbracoUSyncGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.Frontend.Umbraco
*
!.gitignore
				</Text>
			</TprFrontendUmbracoUSyncGitIgnoreText>
			<TprFrontendUmbracoUSyncGitIgnore Include="%(TprFrontendUmbracoUSyncGitIgnoreText.Text)" />
		</ItemGroup>
		<Message Text="ThePensionsRegulator.Frontend.Umbraco generating $(ProjectDir)uSync\.gitignore to prevent commit of uSync files copied into the project." Importance="high" />
		<WriteLinesToFile File="$(ProjectDir)uSync\ThePensionsRegulator.Frontend.Umbraco\.gitignore" Lines="@(TprFrontendUmbracoUSyncGitIgnore)" Overwrite="True"/>
	</Target>

	<Target Name="TprFrontendUmbraco_Cleanup" BeforeTargets="BeforeBuild">
		<!-- Clean up obsolete files from previous versions where they would cause a conflict. -->
		<ItemGroup>
			<TprFrontendUmbraco_uSyncVersion Include="v9"/>
			<TprFrontendUmbraco_uSyncVersion Include="v17"/>
		</ItemGroup>
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardscard.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardscard.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordion.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordion.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordionsection.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordionsection.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordionsectionsettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordionsectionsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordionsettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpraccordionsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbacktomenu.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbacktomenu.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbacktomenusettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbacktomenusettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbacktotop.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbacktotop.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbox.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprbox.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprboxsettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprboxsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprcontextbar1.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprcontextbar1.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprcontextbar2.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprcontextbar2.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprcontextbar3.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprcontextbar3.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocument.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocument.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocuments.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocuments.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocumentsettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocumentsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocumentssettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprdocumentssettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprfeaturedimage.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprfeaturedimage.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprfeaturedimagesettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprfeaturedimagesettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprfooter.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprfooter.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheader.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheader.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenu.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenu.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenuchilditem.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenuchilditem.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenuparentitem.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenuparentitem.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenuitem.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprheadermenuitem.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprimage.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprimage.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprimagesettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprimagesettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprnestedbox.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprnestedbox.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprnestedboxsettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprnestedboxsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprrelatedlinks.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprrelatedlinks.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprrelatedlinkssettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprrelatedlinkssettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsearchresults.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsearchresults.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsearchresultssettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsearchresultssettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncard.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncard.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncards.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncards.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardschildren.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardschildren.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardsettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardsettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardssettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tprsectioncardssettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpryoutubevideo.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpryoutubevideo.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpryoutubevideosettings.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\ContentTypes\tpryoutubevideosettings.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRSectionCardsCardDescriptionRichTextEditor.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRSectionCardsCardDescriptionRichTextEditor.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRSectionCardsCardTextarea.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRSectionCardsCardTextarea.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\YoutubeVideoSettingsAutoplayToggle.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\YoutubeVideoSettingsAutoplayToggle.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\YoutubeVideoSettingsPlaysInLineToggle.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\YoutubeVideoSettingsPlaysInLineToggle.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\YoutubeVideoSettingsPreloadDropdown.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\YoutubeVideoSettingsPreloadDropdown.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRAccordionBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRAccordionBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRAccordionSectionBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRAccordionSectionBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBoxColour.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBoxColour.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBoxStyle.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRBoxStyle.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRDocumentsBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRDocumentsBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFeaturedImageBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFeaturedImageBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFeaturedImageSettingsHorizontalToggle.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFeaturedImageSettingsHorizontalToggle.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFooterBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFooterBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFooterLanguageCodeRadioButtonList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFooterLanguageCodeRadioButtonList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFooterThreeColumnLinksBlockGrid.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRFooterThreeColumnLinksBlockGrid.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuChildItemBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuChildItemBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuParentItemBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuParentItemBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuItemBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeaderMenuItemBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeadingLevelSearchResults.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeadingLevelSearchResults.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeadingLevelSectionCards.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRHeadingLevelSectionCards.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRImageSize.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRImageSize.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRNestedBoxStyle.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRNestedBoxStyle.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRRichTextEditorHeaderAndFooter.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRRichTextEditorHeaderAndFooter.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRRichTextEditorSectionCard.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRRichTextEditorSectionCard.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRSectionCardsBlockList.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRSectionCardsBlockList.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRYouTubeVideoSettingsAutoplay.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRYouTubeVideoSettingsAutoplay.config')" />
		<Delete Files="$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRYouTubeVideoSettingsPlaysInline.config" Condition="Exists('$(ProjectDir)uSync\%(TprFrontendUmbraco_uSyncVersion.Identity)\DataTypes\TPRYouTubeVideoSettingsPlaysInline.config')" />
	</Target>
</Project>
