<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>$(AssemblyName)</Title>
		<Authors>rickmason-tpr</Authors>
		<Company>The Pensions Regulator</Company>
		<Description>Umbraco support for components targeted at The Pensions Regulator.</Description>
		<Copyright>The Pensions Regulator</Copyright>
		<PackageProjectUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</PackageProjectUrl>
		<RepositoryUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</RepositoryUrl>
		<PackageReadmeFile>NuGetReadme.md</PackageReadmeFile>
		<PackageIcon>tpr-nuget.png</PackageIcon>
		<RepositoryType>git</RepositoryType>
		<PackageTags>gds govuk gov.uk umbraco blocklist blockgrid</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>$(AssemblyName)</PackageId>
		<Product>$(AssemblyName)</Product>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Backoffice\node_modules\**" />
	  <Content Remove="Backoffice\node_modules\**" />
	  <EmbeddedResource Remove="Backoffice\node_modules\**" />
	  <None Remove="Backoffice\node_modules\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="Backoffice\package-lock.json" />
		<Content Remove="Backoffice\package.json" />
		<Content Remove="Backoffice\public\umbraco-package.json" />
		<Content Remove="Backoffice\tsconfig.json" />
		<Content Remove="sasscompiler.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="ThePensionsRegulator.Frontend.Umbraco.targets">
		  <PackagePath>build;buildTransitive</PackagePath>
		  <Pack>true</Pack>
		</Content>
		<Content Include="ThePensionsRegulator.Frontend.Umbraco.generated.props">
			<PackagePath>build</PackagePath>
			<Pack>true</Pack>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.SassCompiler" Version="1.86.2" />
		<PackageReference Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="17.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GovUk.Frontend.AspNetCore.Extensions\GovUk.Frontend.AspNetCore.Extensions.csproj" />
		<ProjectReference Include="..\GovUk.Frontend.Umbraco\GovUk.Frontend.Umbraco.csproj" />
		<ProjectReference Include="..\ThePensionsRegulator.Frontend\ThePensionsRegulator.Frontend.csproj" />
		<ProjectReference Include="..\ThePensionsRegulator.Umbraco.Core\ThePensionsRegulator.Umbraco.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\tpr-nuget.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="Backoffice\package-lock.json" />
		<None Include="Backoffice\package.json">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Include="Backoffice\public\umbraco-package.json">
		  <Pack>false</Pack>
		</None>
		<None Include="Backoffice\tsconfig.json" />
		<None Include="sasscompiler.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Backoffice\src\blocks\helpers\media-helper.ts">
	    <SubType>Code</SubType>
	  </None>
	  <None Update="NuGetReadme.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="Styles\tpr.scss">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </None>
	  <None Update="Styles\govuk-umbraco-backoffice.scss">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\tpr.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Backoffice\node_modules\**" />
	</ItemGroup>
</Project>