<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Title>$(AssemblyName)</Title>
	<Authors>rickmason-tpr</Authors>
	<Company>The Pensions Regulator</Company>
	<Description>Helper code for unit testing Umbraco applications, and in particular applications built using ThePensionsRegulator.Umbraco.</Description>
	<Copyright>The Pensions Regulator</Copyright>
	<PackageProjectUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</PackageProjectUrl>
	<PackageIcon>tpr-nuget.png</PackageIcon>
	<PackageReadmeFile>NuGetReadme.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageTags>gds govuk gov.uk umbraco blocklist testing unittest umbraco-marketplace</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<IncludeSymbols>True</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<PackageId>$(AssemblyName)</PackageId>
	<Product>$(AssemblyName)</Product>
  </PropertyGroup>

  <ItemGroup>
	<None Include="..\tpr-nuget.png">
	  <Pack>True</Pack>
	  <PackagePath>\</PackagePath>
	</None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="ThePensionsRegulator.Analyzers.Umbraco" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThePensionsRegulator.Umbraco.Core\ThePensionsRegulator.Umbraco.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NuGetReadme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
