import type { AddressLookupContent } from "../Scripts/address-lookup/types.js";

export function createMockAddressLookupContent(): AddressLookupContent {
    return {
        addressLookupLegend: "Find address",
        addressLookupHint: "lookup hint",
        addressLine1Label: "Address line 1",
        addressLine1RequiredErrorMessage: "Address line 1 is required",
        addressLine1MaxLengthErrorMessage: "Address line 1 must be 100 characters or fewer",
        addressLine2Label: "Address line 2",
        addressLine2MaxLengthErrorMessage: "Address line 2 must be 100 characters or fewer",
        addressLine3Label: "Address line 3",
        addressLine3MaxLengthErrorMessage: "Address line 3 must be 100 characters or fewer",
        postTownLabel: "Town or city",
        postTownRequiredErrorMessage: "Enter a post town",
        postTownMaxLengthErrorMessage: "Town or city must be 100 characters or fewer",
        countyLabel: "County",
        countyMaxLengthErrorMessage: "County must be 100 characters or fewer",
        countyStateProvinceLabel: "County or state",
        countyStateProvinceMaxLengthErrorMessage: "County or state must be 100 characters or fewer",
        postcodeLabel: "Postcode",
        postcodeRequiredErrorMessage: "Enter a postcode",
        postcodeMaxLengthErrorMessage: "Postcode must be 10 characters or fewer",
        postcodePatternErrorMessage: "Enter a valid postcode",
        countryLabel: "Country",
        countrySelectPlaceholder: "Select a country",
        countryRequiredErrorMessage: "Select a country",
        buildingNameOrNumberLabel: "Building name or number",
        ukManualEntryLinkLabel: "Enter a UK address manually",
        ukManualEntryLegend: "Enter a UK address",
        internationalManualEntryLabel: "Enter an international address",
        internationalManualEntryLegend: "Enter an international address",
        findAddressButton: "Find address",
        addressNotFoundMessage: "No addresses found",
        serviceUnavailableMessage: "Service unavailable",
        addressSelectLabel: "Select an address",
        confirmAddressLabel: "Confirm address",
        backToPostcodeSearchLabel: "Back to postcode search",
        changeAddressLabel: "Change address",
        addressSelectErrorMessage: "Select an address to continue",
        internationalManualEntryNotConfirmedErrorMessage: "Confirm the international address",
        ukManualEntryNotConfirmedErrorMessage: "Confirm the UK address",
        resultsNotConfirmedErrorMessage: "Confirm the selected address",
        searchNotConfirmedErrorMessage: "Confirm the search results"
    };
}
