<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<!-- This file is run automatically when the project is built. https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019 
	     Run a custom command using Dart SASS installed by the AspNetCore.SassCompiler NuGet package. The default package configuration cannot be used
		 because in Release configuration it removes the comments that are needed to configure the Umbraco rich text editor.
		 -->
<!-- uSync files are authored in GovUk.Frontend.Umbraco.ExampleApp. Copy here to include them in the NuGet package. 
		 They must be physically present in the project folder to generate a reference in the <contentFiles> section of the .nuspec file. 
		 If that reference is missing the consuming project will report a build error. -->
	<Target Name="GovUkFrontendUmbraco_CopyUSync" BeforeTargets="BeforeBuild">
		<ItemGroup>
			<DataTypes Include="..\GovUk.Frontend.Umbraco.ExampleApp\uSync\v9\DataTypes\GOVUK*.config"></DataTypes>
			<ContentTypes Include="..\GovUk.Frontend.Umbraco.ExampleApp\uSync\v9\ContentTypes\govuk*.config"></ContentTypes>
		</ItemGroup>
		<Copy SourceFiles="@(DataTypes)"
			DestinationFiles="$(ProjectDir)uSync\v9\DataTypes\%(RecursiveDir)%(Filename)%(Extension)" />
		<Copy SourceFiles="@(ContentTypes)"
			DestinationFiles="$(ProjectDir)uSync\v9\ContentTypes\%(RecursiveDir)%(Filename)%(Extension)" />
	</Target>

</Project>
