<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>ThePensionsRegulator.$(AssemblyName)</Title>
		<Authors>rickmason-tpr</Authors>
		<Company>The Pensions Regulator</Company>
		<Description>GOV.UK Design System components implemented using the block list editor in Umbraco, and classes used to build applications based on these components.</Description>
		<Copyright>The Pensions Regulator</Copyright>
		<PackageProjectUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</PackageProjectUrl>
		<RepositoryUrl>https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions</RepositoryUrl>
		<PackageReadmeFile>NuGetReadme.md</PackageReadmeFile>
		<PackageIcon>tpr-nuget.png</PackageIcon>
		<RepositoryType>git</RepositoryType>
		<PackageTags>gds govuk gov.uk umbraco blocklist blockgrid umbraco-marketplace</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>ThePensionsRegulator.$(AssemblyName)</PackageId>
		<Product>ThePensionsRegulator.$(AssemblyName)</Product>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="sasscompiler.json" />
		<Compile Remove="App_Plugins\GOVUK\blocks\controllers\**" />
		<Content Remove="App_Plugins\GOVUK\blocks\controllers\**" />

		<!-- Dont include the Backoffice folder as part of packaging nuget build -->
		<Content Remove="Backoffice\**" />
		<EmbeddedResource Remove="App_Plugins\GOVUK\blocks\controllers\**" />
		<None Remove="App_Plugins\GOVUK\blocks\controllers\**" />

		<!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
		<None Include="Backoffice\public\umbraco-package.json" Pack="false" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="App_Plugins\GOVUK\blocks\views\GovUkAccordion.html" />
	  <None Remove="App_Plugins\GOVUK\blocks\views\GovUkFileUploadPreview.html" />
	  <None Remove="App_Plugins\GOVUK\tinymce\paste-from-word.min.js" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkCheckbox.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkCheckboxesPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkDateInputPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkFieldset.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkGridColumns.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkNotificationBannerPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkPagination.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkPanelPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkRadiosPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkFileUploadPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkSelectPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkSummaryCardPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkAccordion.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkSummaryListPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkTaskListPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkTaskListSummary.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkTextAreaPreview.html" />
		<Content Include="App_Plugins\GOVUK\blocks\views\GovUkTextInputPreview.html" />
		<Content Include="App_Plugins\GOVUK\govuk.controller.js" />
		<Content Include="App_Plugins\GOVUK\govuk.css" />
		<Content Include="App_Plugins\GOVUK\model-property.html" />
		<Content Include="App_Plugins\GOVUK\package.manifest" />
		<Content Include="App_Plugins\GOVUK\tinymce\paste-from-word.min.js" />
		<Content Include="Styles\_govuk-spacing.scss" />
		<Content Include="Styles\_govuk-list.scss" />
		<Content Include="ThePensionsRegulator.GovUk.Frontend.Umbraco.targets">
		  <PackagePath>build;buildTransitive</PackagePath>
		  <Pack>true</Pack>
		</Content>
		<Content Include="Styles\govuk-umbraco-backoffice.css">
			<PackagePath>contentFiles\any\$(TargetFramework)\Content\css</PackagePath>
			<Pack>true</Pack>
		</Content>
		<Content Include="Styles\govuk-umbraco-backoffice.css.map">
			<PackagePath>contentFiles\any\$(TargetFramework)\Content\css</PackagePath>
			<Pack>true</Pack>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.SassCompiler" Version="1.86.2" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="17.0.2" />
		<PackageReference Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="17.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GovUk.Frontend.AspNetCore.Extensions\GovUk.Frontend.AspNetCore.Extensions.csproj" />
		<ProjectReference Include="..\ThePensionsRegulator.Umbraco\ThePensionsRegulator.Umbraco.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\tpr-nuget.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="sasscompiler.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="NuGetReadme.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="Styles\govuk-frontend.scss">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </None>
	  <None Update="Styles\govuk-umbraco-backoffice.scss">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\_govuk-list.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\govuk-umbraco-backoffice.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\govuk-frontend.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\_backoffice-block-views.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="Styles\_backoffice-rich-text-formats.scss" />
	</ItemGroup>

	<ItemGroup>
	  <UpToDateCheckInput Remove="App_Plugins\GOVUK\blocks\controllers\**" />
	</ItemGroup>
</Project>