<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\build\ThePensionsRegulator.GovUk.Frontend.Umbraco.generated.props"/>
	
	<Target Name="ThePensionsRegulatorGovUkFrontendUmbraco" AfterTargets="ThePensionsRegulatorGovUkFrontend">
		<!-- Determine if the consuming project is a web project. If it isn't then skip copying/generating files. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/@Sdk">
			<Output TaskParameter="Result" ItemName="GovUkFrontendUmbraco_TargetProjectSdk" />
		</XmlPeek>
		<PropertyGroup>
			<GovUkFrontendUmbraco_TargetProjectIsWebProject Condition="@(GovUkFrontendUmbraco_TargetProjectSdk)=='Microsoft.NET.Sdk.Web'">true</GovUkFrontendUmbraco_TargetProjectIsWebProject>
		</PropertyGroup>

		<!-- Copy files from this project to the consuming project. -->
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco not copying uSync and CSS files because the target project is not a web project." Condition="$(GovUkFrontendUmbraco_TargetProjectIsWebProject) != true" Importance="high" />
		<CallTarget Targets="GovUkFrontendUmbraco_CopyFiles" Condition="$(GovUkFrontendUmbraco_TargetProjectIsWebProject) == true" />

		<!-- If the ModelsBuilder out-of-date flag is present, show a helpful warning. -->
		<Warning Text="Umbraco Models Builder models are out-of-date. Go to Settings &gt; Models Builder &gt; Generate models in the Umbraco backoffice to update them." Condition="Exists('$(ProjectDir)Models\ModelsBuilder\ood.flag')" />
	</Target>

	<Target Name="GovUkFrontendUmbraco_CopyFiles">
		<!-- Use the version of this package to find the NuGet package folder, and copy files from the package to the consuming project. -->
		<PropertyGroup>
			<GovUkFrontendUmbraco_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</GovUkFrontendUmbraco_UserProfile>
			<GovUkFrontendUmbraco_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</GovUkFrontendUmbraco_UserProfile>
			<GovUkFrontendUmbraco_ContentFilesPath>$(GovUkFrontendUmbraco_UserProfile)\.nuget\packages\thepensionsregulator.govuk.frontend.umbraco\$(TprGovUkFrontendUmbracoPackageVersion)\contentFiles\any\$(TargetFramework)\</GovUkFrontendUmbraco_ContentFilesPath>
			<GovUkFrontendUmbraco_StaticWebAssetsPath>$(GovUkFrontendUmbraco_UserProfile)\.nuget\packages\thepensionsregulator.govuk.frontend.umbraco\$(TprGovUkFrontendUmbracoPackageVersion)\staticwebassets\ThePensionsRegulator.GovUk.Frontend.Umbraco\</GovUkFrontendUmbraco_StaticWebAssetsPath>
		</PropertyGroup>
		<ItemGroup>
			<uSyncFilesFromGovUkFrontendUmbraco Include="$(GovUkFrontendUmbraco_ContentFilesPath)uSync\**" />
			<GovUkFrontendUmbraco_BackofficeCss Include="$(GovUkFrontendUmbraco_StaticWebAssetsPath)css\govuk-umbraco-backoffice.*" />
		</ItemGroup>

		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco copying uSync files from $(GovUkFrontendUmbraco_ContentFilesPath) to $(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(uSyncFilesFromGovUkFrontendUmbraco)"
			  DestinationFiles="$(ProjectDir)uSync\%(RecursiveDir)%(Filename)%(Extension)" />

		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco copying backoffice CSS files from $(GovUkFrontendUmbraco_StaticWebAssetsPath) to $(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(GovUkFrontendUmbraco_BackofficeCss)"
			  DestinationFiles="$(ProjectDir)wwwroot\css\%(RecursiveDir)%(Filename)%(Extension)" />

		<!-- Rich text editor data types import wwwroot\css\site.css so that consuming projects can add their own styles, including styles for the 'Formats' dropdown.
		     However if there is no site.css the backoffice generates a request with a 404 response, so create a placeholder file to respond to that request. -->
		<PropertyGroup>
			<GenerateUmbracoSiteCss Condition="!Exists('$(ProjectDir)wwwroot\css\site.css') and !Exists('$(ProjectDir)Styles\site.scss')">true</GenerateUmbracoSiteCss>
		</PropertyGroup>
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco generating $(ProjectDir)wwwroot\css\site.css because it does not exist." Importance="high" Condition="$(GenerateUmbracoSiteCss) == true" />
		<ItemGroup>
			<GovUkFrontendUmbracoSiteCssText Include="GovUkFrontendUmbracoSiteCssText">
				<Text>
/* Generated by ThePensionsRegulator.GovUk.Frontend.Umbraco for the Umbraco rich text editor.
   You can delete this file safely and replace it with your own site.css */
				</Text>
			</GovUkFrontendUmbracoSiteCssText>
			<GovUkFrontendUmbracoSiteCss Include="%(GovUkFrontendUmbracoSiteCssText.Text)" />
		</ItemGroup>
		<WriteLinesToFile File="$(ProjectDir)wwwroot\css\site.css" Lines="@(GovUkFrontendUmbracoSiteCss)" Overwrite="False" Condition="$(GenerateUmbracoSiteCss) == true" />

		<!-- Generate .gitignore files so that files copied from this package are not committed to the consuming project's source control.	 
			 Only do that if the folder exists, otherwise they'll also get created in a test project with a project reference to the target project. -->
		<ItemGroup>
			<GovUkFrontendUmbracoCssGitIgnoreText Include="GovUkFrontendUmbracoCssGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.GovUk.Frontend.Umbraco
govuk-umbraco-backoffice.css
govuk-umbraco-backoffice.css.map
				</Text>
			</GovUkFrontendUmbracoCssGitIgnoreText>
			<GovUkFrontendUmbracoCssGitIgnore Include="%(GovUkFrontendUmbracoCssGitIgnoreText.Text)" />
		</ItemGroup>
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco generating $(ProjectDir)wwwroot\css\.gitignore to prevent commit of backoffice CSS files copied into the project." Importance="high" Condition="Exists('$(ProjectDir)wwwroot\css')" />
		<WriteLinesToFile File="$(ProjectDir)wwwroot\css\.gitignore" Lines="@(GovUkFrontendUmbracoCssGitIgnore)" Overwrite="True" />

		<ItemGroup>
			<GovUkFrontendUmbracoUSyncGitIgnoreText Include="GovUkFrontendUmbracoUSyncGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.GovUk.Frontend.Umbraco
**/govuk*.config
**/GOVUK*.config
				</Text>
			</GovUkFrontendUmbracoUSyncGitIgnoreText>
			<GovUkFrontendUmbracoUSyncGitIgnore Include="%(GovUkFrontendUmbracoUSyncGitIgnoreText.Text)" />
		</ItemGroup>
		<Message Text="ThePensionsRegulator.GovUk.Frontend.Umbraco generating $(ProjectDir)uSync\.gitignore to prevent commit of uSync files copied into the project." Importance="high" Condition="Exists('$(ProjectDir)uSync')" />
		<WriteLinesToFile File="$(ProjectDir)uSync\.gitignore" Lines="@(GovUkFrontendUmbracoUSyncGitIgnore)" Overwrite="True" />
	</Target>
</Project>
