<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\build\ThePensionsRegulator.GovUk.Frontend.generated.props"/>

	<Target Name="ThePensionsRegulatorGovUkFrontend" BeforeTargets="BeforeBuild">
		<!-- Determine if the consuming project is a web project. If it isn't then skip copying/generating files. -->
		<XmlPeek XmlInputPath="$(MSBuildProjectFullPath)" Query="Project/@Sdk">
			<Output TaskParameter="Result" ItemName="TprGovUkFrontend_TargetProjectSdk" />
		</XmlPeek>
		<PropertyGroup>
			<TprGovUkFrontend_TargetProjectIsWebOrRclProject Condition="@(TprGovUkFrontend_TargetProjectSdk)=='Microsoft.NET.Sdk.Web' Or @(TprGovUkFrontend_TargetProjectSdk)=='Microsoft.NET.Sdk.Razor'">true</TprGovUkFrontend_TargetProjectIsWebOrRclProject>
		</PropertyGroup>

		<!-- Copy files from this project to the consuming project. -->
		<Message Text="ThePensionsRegulator.GovUk.Frontend not copying SASS files because the target project is not a web project or Razor class library." Condition="$(TprGovUkFrontend_TargetProjectIsWebOrRclProject) != true" Importance="high" />
		<CallTarget Targets="TprGovUkFrontend_CopyFiles" Condition="$(TprGovUkFrontend_TargetProjectIsWebOrRclProject) == true" />
	</Target>

	<Target Name="TprGovUkFrontend_CopyFiles">
		<!-- Use the version of this package to find the NuGet package folder, and copy files from the package to the consuming project. -->
		<PropertyGroup>
			<TprGovUkFrontend_StylesFolderExists Condition="Exists('$(ProjectDir)Styles')">true</TprGovUkFrontend_StylesFolderExists>
			<TprGovUkFrontend_UserProfile Condition=" '$(OS)' == 'Windows_NT' ">$(UserProfile)</TprGovUkFrontend_UserProfile>
			<TprGovUkFrontend_UserProfile Condition=" '$(OS)' != 'Windows_NT' ">$(HOME)</TprGovUkFrontend_UserProfile>
			<ThePensionsRegulatorGovUkFrontendSassFolder>$(TprGovUkFrontend_UserProfile)\.nuget\packages\thepensionsregulator.govuk.frontend\$(TprGovUkFrontendPackageVersion)\Styles\</ThePensionsRegulatorGovUkFrontendSassFolder>
		</PropertyGroup>
		<ItemGroup>
			<ThePensionsRegulatorGovUkFrontendSassFiles Include="$(ThePensionsRegulatorGovUkFrontendSassFolder)**\*.scss" />
		</ItemGroup>

		<Message Text="ThePensionsRegulator.GovUk.Frontend not copying SASS files because $(ProjectDir)Styles does not exist." Importance="high" Condition="$(TprGovUkFrontend_StylesFolderExists) != true" />
		<Message Text="ThePensionsRegulator.GovUk.Frontend copying SASS files from $(ThePensionsRegulatorGovUkFrontendSassFolder) to $(ProjectDir)." Importance="high" Condition="$(TprGovUkFrontend_StylesFolderExists) == true" />

		<Copy SourceFiles="@(ThePensionsRegulatorGovUkFrontendSassFiles)"
			  DestinationFiles="$(ProjectDir)Styles\%(RecursiveDir)%(Filename)%(Extension)"
			  Condition="$(TprGovUkFrontend_StylesFolderExists) == true"
			  SkipUnchangedFiles="true"/>

		<!-- Generate a .gitignore so that govuk-frontend SASS files copied from this package are not committed to the consuming project's source control.
			 Only do that if the folder exists, otherwise they'll also get created in an projects with no interest in SASS. -->
		<Message Text="ThePensionsRegulator.GovUk.Frontend generating $(ProjectDir)Styles\govuk\.gitignore to prevent commit of SASS files copied into the project." Importance="high" Condition="$(TprGovUkFrontend_StylesFolderExists) == true" />
		<ItemGroup>
			<ThePensionsRegulatorGovUkFrontendGitIgnoreText Include="ThePensionsRegulatorGovUkFrontendGitIgnoreText">
				<Text>
# Generated by ThePensionsRegulator.GovUk.Frontend
*
!.gitignore
				</Text>
			</ThePensionsRegulatorGovUkFrontendGitIgnoreText>
			<ThePensionsRegulatorGovUkFrontendGitIgnore Include="%(ThePensionsRegulatorGovUkFrontendGitIgnoreText.Text)" />
		</ItemGroup>
		<WriteLinesToFile File="$(ProjectDir)Styles\govuk\.gitignore" Lines="@(ThePensionsRegulatorGovUkFrontendGitIgnore)" Overwrite="True" Condition="$(TprGovUkFrontend_StylesFolderExists) == true" />
	</Target>
	
	<!-- In pipeline builds if a CSS file exists AspNetCore.SassCompiler won't overwrite it with the generated version, 
	    so look for SCSS files which will generate CSS files, and delete the equivalent CSS file first -->
	<Target Name="ThePensionsRegulatorGovUkFrontend_CleanGeneratedCss" BeforeTargets="CoreClean">
		<ItemGroup>
			<ScssSourceFiles Include="$(MSBuildProjectDirectory)\Styles\*.scss" Exclude="$(MSBuildProjectDirectory)\Styles\_*.scss" />
		</ItemGroup>
		<ItemGroup>
			<FilesToDeleteStep1 Include="@(ScssSourceFiles->Replace('$(MSBuildProjectDirectory)\Styles', '$(MSBuildProjectDirectory)\wwwroot\css'))" />
		</ItemGroup>
		<ItemGroup>
			<FilesToDeleteStep2 Include="@(FilesToDeleteStep1->Replace('.scss', '.css'))" />
		</ItemGroup>

		<Delete Files="@(FilesToDeleteStep2)"  />
	</Target>

</Project>
